In [1]:
import pandas as pd
df1 = pd.read_csv('../dados/nao_tratados/base_dashboard_mensal.csv', sep=';', encoding='utf-8-sig')
df2 = pd.read_csv('../dados/nao_tratados/internacoes_municipio_mensal.csv', sep=';', encoding='utf-8-sig')
df3 = pd.read_csv('../dados/nao_tratados/poluentes_mensal.csv', sep=';', encoding='utf-8-sig')

In [2]:
#Padronizar nomes dos municipios (Primeira Letra Maiúscula)
df2['municipio'] = df2['municipio'].str.title()

In [3]:
# 1. Garante que valores vazios não quebrem o código e converte para Int (remove o .0)
# 2. Converte para String logo em seguida
df2['cod_municipio'] = df2['cod_municipio'].astype(str).str.replace('.0', '', regex=False)
df2['cod_municipio'] = df2['cod_municipio'].astype(str).str.replace('.0', '', regex=False)

# O tipo 'Int64' (com I maiúsculo) permite inteiros mesmo com valores vazios (NaN)
df2['ano'] = df2['ano'].astype('Int64')
df2['mes'] = df2['mes'].astype('Int64')
df2.head()

,cod_municipio,municipio,ano,mes,periodo,internacoes,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,320010,Afonso Claudio,2024,1,2024-01,19,NaN,NaN,NaN,NaN,NaN,NaN
1,320010,Afonso Claudio,2024,2,2024-02,16,NaN,NaN,NaN,NaN,NaN,NaN
2,320010,Afonso Claudio,2024,3,2024-03,11,NaN,NaN,NaN,NaN,NaN,NaN
3,320010,Afonso Claudio,2024,4,2024-04,29,NaN,NaN,NaN,NaN,NaN,NaN
4,320010,Afonso Claudio,2024,5,2024-05,25,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Garante que a coluna seja numérica (inteiro)
df1['internacoes_total'] = df1['internacoes_total'].astype(int)

In [12]:
# Garante que a coluna seja numérica (inteiro)
#df2['internacoes'] = df2['internacoes'].astype(int)
#df2['internacoes'] = df2['internacoes'].astype('Int64')
# 1. Converte para numérico forçando erros a virarem NaN (vazio)
# Isso faz o Python ignorar os traços '---' e textos
df2['internacoes'] = pd.to_numeric(df2['internacoes'], errors='coerce')

# 2. Preenche os campos que eram '---' (agora NaN) com 0
df2['internacoes'] = df2['internacoes'].fillna(0)

# 3. Agora sim, converte para inteiro com segurança
df2['internacoes'] = df2['internacoes'].astype(int)

# Verificação:
#print(df2['internacoes'].dtype) # Deve mostrar int32 ou int64
df2.head()

,cod_municipio,municipio,ano,mes,periodo,internacoes,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,320010.0,Afonso Claudio,2024.0,1.0,2024-01,19,NaN,NaN,NaN,NaN,NaN,NaN
1,320010.0,Afonso Claudio,2024.0,2.0,2024-02,16,NaN,NaN,NaN,NaN,NaN,NaN
2,320010.0,Afonso Claudio,2024.0,3.0,2024-03,11,NaN,NaN,NaN,NaN,NaN,NaN
3,320010.0,Afonso Claudio,2024.0,4.0,2024-04,29,NaN,NaN,NaN,NaN,NaN,NaN
4,320010.0,Afonso Claudio,2024.0,5.0,2024-05,25,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Vírgula por Ponto
df1['PM10'] = df1['PM10'].astype(str).str.replace(',', '.').astype(float)
df1['PM25'] = df1['PM25'].astype(str).str.replace(',', '.').astype(float)
df1['NO2'] = df1['NO2'].astype(str).str.replace(',', '.').astype(float)
df1['SO2'] = df1['SO2'].astype(str).str.replace(',', '.').astype(float)
df1['CO'] = df1['CO'].astype(str).str.replace(',', '.').astype(float)
df1['O3'] = df1['O3'].astype(str).str.replace(',', '.').astype(float)

df1.head()

In [4]:
# Remove colunas onde TODOS os valores são nulos (NaN)
df1 = df1.dropna(axis=1, how='all')
df2 = df2.dropna(axis=1, how='all')
df3 = df3.dropna(axis=1, how='all')
df2.head()

  cod_municipio       municipio   ano  mes  periodo internacoes
0        320010  Afonso Claudio  2024    1  2024-01          19
1        320010  Afonso Claudio  2024    2  2024-02          16
2        320010  Afonso Claudio  2024    3  2024-03          11
3        320010  Afonso Claudio  2024    4  2024-04          29
4        320010  Afonso Claudio  2024    5  2024-05          25

In [5]:
# Criando os novos arquivos limpos
# index=False evita que o Pandas crie uma coluna extra de números (0, 1, 2...)
#df1.to_csv('../dados/base_dashboard_mensal_limpa.csv', index=False, sep=';', encoding='utf-8-sig')
df2.to_csv('../dados/internacoes_municipio_mensal_limpa.csv', index=False, sep=';', encoding='utf-8-sig')
#df3.to_csv('../dados/poluentes_mensal_limpa.csv', index=False, sep=';', encoding='utf-8-sig')

print("Tabelas salvas com sucesso!")

Tabelas salvas com sucesso!